Visemes Creation
teamneoneko/Avatar-Toolkit pull request #27
Opened 2024-07-08 09:18 UTC by Yusarina

**Do not merge this unto the translations are merge again my main branch is kinda messed up due to not have translation in it's own branch.** 

This is not ready for prime time, I still need to add stuff and make this system better however we need to get the armture slelection done before I continue. However the viseme creation itself seems to work mostly fine, does need a little bit of work though. This is very much isnpired via the Cats one.

To-Do
- Mesh auto detection from selected Armature.
- Auto detection of shapekeys on said mesh.
- Translations.
- Maybe some optimizations on the creation.

2024-07-22 21:25 UTC, Yusarina commented
Fixed Conflicts

2024-07-24 23:41 UTC, 989onan commented
This needs a revisit, we have translations now so this may need conflicts resolved and integrated with translations

2024-07-25 00:42 UTC, 989onan requested changes
Reviewed, needs a small change

2024-07-25 00:42 UTC, 989onan commented on core/common.py
> +def has_shapekeys(mesh_obj: Object) -> bool:
this is instanciated twice, must have done that in the chaos

2024-07-25 00:42 UTC, 989onan commented on core/common.py
> +def has_shapekeys(mesh_obj: Object) -> bool:
other than this, looks good!

2024-07-25 00:43 UTC, Yusarina commented
Oh lol, I already was making changes lol 

- Viesmes will now use selected armature.
- New dropdown menu in the viseme UI so the user can select which mesh to create visemes on.
- New helper function get_armature_meshes
- Added a new check before we create the new visemes to see if any exist, if there do we will remove them and create the new ones.
- fixed several issues and errors.

2024-07-25 00:46 UTC, 989onan approved these changes
looks good, perfect!

2024-07-25 00:46 UTC, merged